# Generated by Django 4.2.20 on 2025-03-20 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60, unique=True)),
                ('company_country', models.CharField(validators=[jobs.models.validate_country])),
                ('company_city', models.CharField(blank=True, max_length=50, null=True)),
                ('company_industry', models.CharField(max_length=50)),
                ('company_website', models.EmailField(max_length=254)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
