# Generated by Django 4.2.20 on 2025-03-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_website',
            field=models.URLField(),
        ),
    ]
